const products = [
  {
    SKU: "SCR-WIB-SS",
    Desc: "POS Staff facing computer",
    Category: "POS",
    Heading: "POS All in One",
    "Part Type": "POS Computer - AIO",
    "Unit Purpose": "All-In-One Point of Sale machine",
    "Model/Part Number": "SCR.WIB.SS",
    "Part Name":
      "Smart screen AiO 15.6” 1920x1080 AIO bare-bone, Gen 11 i5-1145GREprocessor, 802.11 AC, Bluetooth 5.0",
    "Product Image": "SCR.WB.DS.P.png",
    Wattage: "130",
    "Product Price (ex GST)": "2020",
    "Asset?": "Yes",
    "Primary Vendor": "Mitsumaru",
    "In Stock": "72",
  },
  {
    SKU: "1S11T3009VAU",
    Desc: "Small POS PC for Adhoc needs",
    Category: "POS",
    Heading: "POS PC",
    "Part Type": "Adhoc POS (Small Form Factor)",
    "Unit Purpose": "Adhoc POS (Small Form Factor)",
    "Model/Part Number": "1547303",
    "Part Name": "Lenovo ThinkCentre M70q - i5, 16gb ram, 256gb SSD",
    "Product Image": "image.png",
    Wattage: "135",
    "Product Price (ex GST)": "1306.67",
    "Asset?": "",
    "Primary Vendor": "Nuago",
    "In Stock": "7",
  },
  {
    SKU: "SCR-WB-DS",
    Desc: "Customer facing screen for POS",
    Category: "POS",
    Heading: "POS Customer Facing Screen",
    "Part Type": "POS - Customer Facing Screen",
    "Unit Purpose": "Customer Facing Screen",
    "Model/Part Number": "SCR.WB.DS",
    "Part Name":
      'Touch Screen Monitor 15.6" 1080P Touch Panel-Portrait view with 1 camera + metal back cover & AG coating',
    "Product Image": "SCR.WB.DS.P.png",
    Wattage: "24",
    "Product Price (ex GST)": "1250",
    "Asset?": "Yes",
    "Primary Vendor": "Mitsumaru",
    "In Stock": "76",
  },
  {
    SKU: "GFS4470",
    Desc: "Customer Facing Barcode Scanner",
    Category: "POS",
    Heading: "POS App Barcode scanner",
    "Part Type": "POS - Barcode Scanner (CFS)",
    "Unit Purpose": "Customer Facing Barcode Scanner",
    "Model/Part Number": "GFS4470",
    "Part Name": "Gryphon Fixed Barcode scanner USB Interface",
    "Product Image": "image.png",
    Wattage: "5",
    "Product Price (ex GST)": "301.25",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "257",
  },
  {
    SKU: "CJ576120035",
    Desc: "Receipt Printer",
    Category: "POS",
    Heading: "POS Receipt Printer",
    "Part Type": "Receipt Printer",
    "Unit Purpose": "Receipt Printer",
    "Model/Part Number": "TM-T88VI",
    "Part Name": "Epson TM-T82III USB & Parallel Thermal Receipt Printer",
    "Product Image": "image.png",
    Wattage: "36",
    "Product Price (ex GST)": "595",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "76",
  },
  {
    SKU: "QBT2430-BK-BTK1",
    Desc: "Drive Through Barcode Scanner",
    Category: "POS",
    Heading: "POS BT Barcode Scanner",
    "Part Type": "POS - DT Barcode Scanner",
    "Unit Purpose": "Drive Through Barcode Scanner",
    "Model/Part Number": "QBT2430-BK-BTK1",
    "Part Name": "Datalogic: QuickScan Handheld + Blue Tooth barcode scanner",
    "Product Image": "image.png",
    Wattage: "21",
    "Product Price (ex GST)": "439.09",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "35",
  },
  {
    SKU: "GPS4421-BKK1B",
    Desc: "POS Barcode Scanner",
    Category: "POS",
    Heading: "POS Barcode Scanner",
    "Part Type": "POS - Barcode Scanner",
    "Unit Purpose": "POS Barcode Scanner",
    "Model/Part Number": "GPS4421-BK-KIT",
    "Part Name": "Datalogic: GPS4421-BKK1B - Gryphon 2D USB barcode Scanner",
    "Product Image": "GPS4421-BKK1B",
    Wattage: "20",
    "Product Price (ex GST)": "199.7",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "70",
  },
  {
    SKU: "CB910B",
    Desc: "POS Cash Drawer",
    Category: "POS",
    Heading: "Cash Drawer",
    "Part Type": "Cash Drawer",
    "Unit Purpose": "Cash Drawer",
    "Model/Part Number": "CB-910B",
    "Part Name": "Nexa - Cash Drawer",
    "Product Image": "image.png",
    Wattage: "5",
    "Product Price (ex GST)": "85.75",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "25",
  },
  {
    SKU: "A225280944 TM7117E00400",
    Desc: "Touch screen monitor for Staff Coffee KDS",
    Category: "KDS",
    Heading: "Coffee Staff Display",
    "Part Type": "Primary KDS - Operator Touch Screen",
    "Unit Purpose": "Ccoffee/OTR App KDS Display",
    "Model/Part Number": "TMELE649473 TM-7117E-B",
    "Part Name":
      'ELO 17" Touch screen monitor + POSIFLEX 17" LCD PCAP Touch Monitor',
    "Product Image": "image.png",
    Wattage: "11.5",
    "Product Price (ex GST)": "731.82",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "9",
  },
  {
    SKU: "TMM30182",
    Desc: "Touch screen monitor for Staff Moes KDS",
    Category: "KDS",
    Heading: "Moes Staff Display",
    "Part Type": "Secondary KDS - Operator Touch Screen",
    "Unit Purpose": "Moes / Diner / QSR / DT Ccoffee KDS Display",
    "Model/Part Number": "TM-3110E-B",
    "Part Name": 'POSIFLEX 9.7" LCD PCAP Touch Monitor',
    "Product Image": "image.png",
    Wattage: "18",
    "Product Price (ex GST)": "394.55",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "16",
  },
  {
    SKU: "6.94538E+11",
    Desc: "Used by POS and KDS for sound",
    Category: "KDS",
    Heading: "Small Speakers",
    "Part Type": "KDS - Speakers",
    "Unit Purpose": "KDS Stereo Speakers",
    "Model/Part Number": "3369",
    "Part Name":
      "Adafruit Mini External USB Stereo Speaker USB Stereo Speaker 2 X 2W, 60dB",
    "Product Image": "image.png",
    Wattage: "5",
    "Product Price (ex GST)": "17",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "84",
  },
  {
    SKU: "HON540V3-B",
    Desc: "Customer Feedback Terminal ",
    Category: "MISC",
    Heading: "Happy or Not Terminal",
    "Part Type": "Happy or Not Terminal (HoN)",
    "Unit Purpose": "Happy or Not Terminal",
    "Model/Part Number": "HON-U",
    "Part Name": "Happy or Not unit (Inc. shipping and setup)",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "339",
    "Asset?": "No",
    "Primary Vendor": "Push My Button (HoN)",
    "In Stock": "1",
  },
  {
    SKU: "PSD2000",
    Desc: "UPS for KDS and POS",
    Category: "KDS",
    Heading: "UPS",
    "Part Type": "KDS/POS - UPS",
    "Unit Purpose": "KDS/POS - UPS",
    "Model/Part Number": "PSD2000",
    "Part Name": "PowerShield Defender 2000VA / 1200W Line Interactive UPS",
    "Product Image": "image.png",
    Wattage: "1200",
    "Product Price (ex GST)": "334.5",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "14",
  },
  {
    SKU: "88984260430 SUF-00006",
    Desc: "Adhoc Mobile POS Solution",
    Category: "POS",
    Heading: "MS Surface Go 3",
    "Part Type": "Tablet - Microsoft Surface",
    "Unit Purpose": "Adhoc Remote POS Solution",
    "Model/Part Number": "SUF-00006",
    "Part Name":
      'Microsoft Surface GO2 LTE Core m3 10.5" Business Tablet (8GB/128GB)',
    "Product Image": "image.png",
    Wattage: "7.5",
    "Product Price (ex GST)": "1096.36",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "9",
  },
  {
    SKU: "PF3-00002",
    Desc: "Docking Station for Surface Tablet",
    Category: "POS",
    Heading: "Surface Go Docking Station",
    "Part Type": "Tablet - Dock",
    "Unit Purpose": "POS Dock Station",
    "Model/Part Number": "PF3-00002",
    "Part Name": "Microsoft Surface Dock Station",
    "Product Image": "image.png",
    Wattage: "200",
    "Product Price (ex GST)": "241.81",
    "Asset?": "Yes",
    "Primary Vendor": "Adelaide Online Computers",
    "In Stock": "35",
  },
  {
    SKU: "1602G2D-2-USB",
    Desc: "BT scanner for Mobile POS solution",
    Category: " POS",
    Heading: "BT Mobile POS Barcode Scanner",
    "Part Type": "POS - Handheld Barcode Scanner (BlueTooth)",
    "Unit Purpose": "Adhoc HandheldBluetooth Barcode Scanner (Mobile POS)",
    "Model/Part Number": "SCHW1602G2D2USBOS",
    "Part Name": "Honeywell Scan Voyager 1602 2D BLUETOOTH KIT",
    "Product Image": "image.png",
    Wattage: "2.5",
    "Product Price (ex GST)": "271.05",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "1",
  },
  {
    SKU: "85252400880",
    Desc: "Protective Case for Surface Tablets",
    Category: "POS",
    Heading: "UAG Protective Case",
    "Part Type": "Tablet - Case w/ Strap",
    "Unit Purpose": "Remote POS Protective Case",
    "Model/Part Number": "UAG Protective Case",
    "Part Name":
      "MICROSOFT UAG PLASMA CASE FOR SURFACE GO WITH HAND AND SHOULDER STRAP",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "86.36",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "3",
  },
  {
    SKU: "",
    Desc: "DMG Terminal & Scanner - Holster",
    Category: "POS",
    Heading: "Mobile POS Holster",
    "Part Type": "DMG Terminal & Scanner - Holster",
    "Unit Purpose": "",
    "Model/Part Number": "",
    "Part Name": "",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "25.32",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "9",
  },
  {
    SKU: "BIM0M53100O",
    Desc: "Fingerprint Scanner for team members to sign in to their shift",
    Category: "Back Office",
    Heading: "Fingerprint Scanner",
    "Part Type": "Fingerprint Scanner",
    "Unit Purpose": "Fingerprint Reader",
    "Model/Part Number": "U.are.U 4500",
    "Part Name": "Digital Persona USB Fingerprint Reader",
    "Product Image": "image.png",
    Wattage: "10",
    "Product Price (ex GST)": "168.18",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "24",
  },
  {
    SKU: "BNUC11TNKi30000 503203720451 73585846514",
    Desc: "KDS System / Back office PC",
    Category: "KDS ",
    Heading: " Small Profile PC (Cubi/ NUC)",
    "Part Type": "Back Office - Small Profile PC",
    "Unit Purpose": "KDS System / Back office PC",
    "Model/Part Number": "BXNUC11i3FNK4",
    "Part Name": "NUC11i3FNK, WIN10 Pro 64",
    "Product Image": "image.png",
    Wattage: "130",
    "Product Price (ex GST)": "970.9",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "17",
  },
  {
    SKU: "73464669654 P29S0534",
    Desc: "Printer for Back office",
    Category: "Back Office",
    Heading: "Back Office Printer",
    "Part Type": "Office Printer",
    "Unit Purpose": "Back Office Printer",
    "Model/Part Number": "LXPMX431ADW",
    "Part Name": "Lexmark MX431ADW MFC",
    "Product Image": "image.png",
    Wattage: "30",
    "Product Price (ex GST)": "423.63",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "24",
  },
  {
    SKU: "CT45-L0N-27D100G",
    Desc: "Mobile computer for stock scanning/ receiving",
    Category: "Back Office",
    Heading: "Handheld PDE",
    "Part Type": "PDE",
    "Unit Purpose": "PDE, Display Kit, Android OS (Honeywell)",
    "Model/Part Number": "CT45-Gen2",
    "Part Name": "Honeywell Gen2, CT45-L0N-1NC11AA",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "1395",
    "Asset?": "Yes",
    "Primary Vendor": "APS Industrial",
    "In Stock": "5",
  },
  {
    SKU: "CT40-HB-UVN-0",
    Desc: "Charger for PDE",
    Category: "Back Office",
    Heading: "PDE - Dock",
    "Part Type": "PDE - Dock",
    "Unit Purpose": "PDE charger base, hub (Honeywell)",
    "Model/Part Number": "CT40-HB-UVN-0",
    "Part Name": "Honeywell CT40-HB (compatible with CT-45)",
    "Product Image": "image.png",
    Wattage: "40",
    "Product Price (ex GST)": "264",
    "Asset?": "No",
    "Primary Vendor": "APS Industrial",
    "In Stock": "43",
  },
  {
    SKU: "8.80609E+11",
    Desc: "OTR / GyG / HJ Operations Tablet PC",
    Category: "Back Office",
    Heading: "Tablet For store",
    "Part Type": "Tablet - Android",
    "Unit Purpose": "OTR / GyG / HJ Operations Tablet PC",
    "Model/Part Number": "SM-X200NZAEXSA",
    "Part Name": 'Samsung A8 64gb WiFi 10" Tablet',
    "Product Image": "image.png",
    Wattage: "45",
    "Product Price (ex GST)": "324.25",
    "Asset?": "Yes",
    "Primary Vendor": "Unified Technology Solutions",
    "In Stock": "81",
  },
  {
    SKU: "",
    Desc: "Screen Protector for Android Tablet",
    Category: "Back Office",
    Heading: "Screen Protector for Android Tablet",
    "Part Type": "Tablet - Android - Screen Protector",
    "Unit Purpose": "",
    "Model/Part Number": "",
    "Part Name": "Samsung A8 Screen Protector",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "62",
    "Asset?": "",
    "Primary Vendor": "",
    "In Stock": "110",
  },
  {
    SKU: "",
    Desc: "Case for Android Tablet",
    Category: "Back Office",
    Heading: "Case for Android Tablet",
    "Part Type": "Tablet - Android - Case",
    "Unit Purpose": "",
    "Model/Part Number": "",
    "Part Name": "Samsung A8 Tablet Cover",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "26",
    "Asset?": "",
    "Primary Vendor": "",
    "In Stock": "15",
  },
  {
    SKU: "66054350341 74218699240",
    Desc: "SMGB Tablet Case",
    Category: "Back Office",
    Heading: "SMGB Tablet Case",
    "Part Type": "Tablet - IPAD - Case",
    "Unit Purpose": "SMGB Tablet Case",
    "Model/Part Number": "66054350341 74218699240",
    "Part Name":
      "Otterbox Defender Case for Apple iPad 10.2 Gen 9 & STM Duxplus Duo",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "84.95",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "16",
  },
  {
    SKU: "571172402673 76539006160",
    Desc: "SMGB Tablet Screen Protector",
    Category: "Back Office",
    Heading: "SMGB Tablet Screen Protector",
    "Part Type": "Tablet - IPAD - Screen Protector",
    "Unit Purpose": "SMGB Tablet Screen Protector",
    "Model/Part Number": "571172402673 79959999714",
    "Part Name":
      "Panzer Glass + Nuglas Tempered Glass Screen Protector for Apple iPad 10.2 Gen 9",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "79.9",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "56",
  },
  {
    SKU: "19425251577",
    Desc: "SMGB Tablet for stores",
    Category: "Back Office",
    Heading: "Ipad",
    "Part Type": "Tablet - IPAD",
    "Unit Purpose": "SMGB Tablet",
    "Model/Part Number": "iPad (9th Gen)",
    "Part Name": 'iPad 10.2" Wi-Fi 64GB  (9th)',
    "Product Image": "image.png",
    Wattage: "20",
    "Product Price (ex GST)": "448.3",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "13",
  },
  {
    SKU: "H6L29AA",
    Desc: "QWERTY Keyboard & Mouse for back office system",
    Category: "Back Office",
    Heading: "Keyboard & Mouse - Wired",
    "Part Type": "Keyboard & Mouse - Wired",
    "Unit Purpose": "QWERTY Keyboard & Mouse for back office system",
    "Model/Part Number": "H6L29AA",
    "Part Name": "HP - USB Essential - Desktop Keyboard & Mouse",
    "Product Image": "image.png",
    Wattage: "10",
    "Product Price (ex GST)": "23.54",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "74",
  },
  {
    SKU: "KEP-USB-M2_R",
    Desc: "RFID Krispy Kreme POS Login Device",
    Category: "Back Office",
    Heading: "POS - RFID Login Device",
    "Part Type": "POS - RFID Login Device",
    "Unit Purpose": "RFID Krispy Kreme POS Login Device",
    "Model/Part Number": "KEP-USB-M2R",
    "Part Name": "AXEZE Clerk POS Reader USB Interface",
    "Product Image": "image.png",
    Wattage: "10",
    "Product Price (ex GST)": "349",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "6",
  },
  {
    SKU: "6.93676E+11",
    Desc: "USB-hub for SMGB BO/POS",
    Category: "MISC",
    Heading: "USB - Hub",
    "Part Type": "USB - Hub",
    "Unit Purpose": "USB-hub for SMGB BO/POS",
    "Model/Part Number": "W5P-U3",
    "Part Name": "Orico 4-Port USB 3.0 Hub with MicroUSB Power Port (100cm)",
    "Product Image": "image.png",
    Wattage: "10",
    "Product Price (ex GST)": "15.6",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "28",
  },
  {
    SKU: "8.71258E+11",
    Desc: "BO Screen / KDS Customer facing screen",
    Category: "Back Office",
    Heading: "Back Office - Monitor",
    "Part Type": "Back Office - Monitor",
    "Unit Purpose": "BO Screen / KDS Customer facing screen",
    "Model/Part Number": "243V7QJAB",
    "Part Name": "Philips - 23.8IN FHD IPS with built in speakers",
    "Product Image": "image.png",
    Wattage: "30",
    "Product Price (ex GST)": "148.18",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "17",
  },
  {
    SKU: "",
    Desc: "Oporto KDS Order Bump Bar",
    Category: "KDS",
    Heading: "KDS - Bump Bar",
    "Part Type": "KDS - Bump Bar",
    "Unit Purpose": "Oporto KDS Order Bump Bar",
    "Model/Part Number": "KBA-BB20-TE-TU-VER-RC",
    "Part Name": "20 Key USB Bump Bar",
    "Product Image": "image.png",
    Wattage: "10",
    "Product Price (ex GST)": "258.18",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "5",
  },
  {
    SKU: "EMB-SNGL",
    Desc: "Enabler - Fuel controller mainly for OPT's/Small fuel-sites",
    Category: "Fuel",
    Heading: "Single Enabler",
    "Part Type": "Fuel Controller - Single Enabler",
    "Unit Purpose":
      "Enabler - Fuel controller mainly for OPT's/Small fuel-sites",
    "Model/Part Number": "EMB",
    "Part Name": "Single Enabler Embedded",
    "Product Image": "image.png",
    Wattage: "80",
    "Product Price (ex GST)": "3995",
    "Asset?": "No",
    "Primary Vendor": "Integration Technologies Limited",
    "In Stock": "6",
  },
  {
    SKU: "EMB-EXPANDED",
    Desc: "Enabler - Fuel controller OTR site default unit",
    Category: "Fuel",
    Heading: "Expanded Enabler",
    "Part Type": "Fuel Controller - Expanded Enabler",
    "Unit Purpose": "Enabler - Fuel controller OTR site default unit",
    "Model/Part Number": "EMBEXPANDED",
    "Part Name": "Expanded Enabler",
    "Product Image": "image.png",
    Wattage: "100",
    "Product Price (ex GST)": "5000",
    "Asset?": "No",
    "Primary Vendor": "Integration Technologies Limited",
    "In Stock": "27",
  },
  {
    SKU: "EMB-DBL",
    Desc: "Enabler - Fuel controller for large fuel-site",
    Category: "Fuel",
    Heading: "Double Expanded Enabler",
    "Part Type": "Fuel Controller - Double Expanded Enabler",
    "Unit Purpose": "Enabler - Fuel controller for large fuel-site",
    "Model/Part Number": "DBLEXPEMB",
    "Part Name": "Double Expanded Enabler",
    "Product Image": "image.png",
    Wattage: "120",
    "Product Price (ex GST)": "5454.55",
    "Asset?": "No",
    "Primary Vendor": "Integration Technologies Limited",
    "In Stock": "1",
  },
  {
    SKU: "2582223",
    Desc: "Enviroled Price sign interface card",
    Category: "Fuel",
    Heading: "PDM258 - Enviroled Interface Card",
    "Part Type": "PDM258 - Enviroled Interface Card",
    "Unit Purpose": "Enviroled Price sign interface card",
    "Model/Part Number": "PDM258",
    "Part Name": "PDM258 : LON",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "175",
    "Asset?": "No",
    "Primary Vendor": "Integration Technologies Limited",
    "In Stock": "56",
  },
  {
    SKU: "DM07171",
    Desc: "Tank gauge / Gilbarco pump interface card",
    Category: "Fuel",
    Heading: "PDM071 - Gilbarco Protocol",
    "Part Type": "PDM071 - Gilbarco Protocol",
    "Unit Purpose": "Tank gauge / Gilbarco pump interface card",
    "Model/Part Number": "PDM071",
    "Part Name": "PDM071: Current Loop",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "175",
    "Asset?": "No",
    "Primary Vendor": "Integration Technologies Limited",
    "In Stock": "33",
  },
  {
    SKU: "1151212",
    Desc: "PEC pump interface card",
    Category: "Fuel",
    Heading: "PDM115 - PEC Protocol",
    "Part Type": "PDM115 - PEC Protocol",
    "Unit Purpose": "PEC pump interface card",
    "Model/Part Number": "PDM115",
    "Part Name": "PDM115: NZ Protocol",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "175",
    "Asset?": "No",
    "Primary Vendor": "Integration Technologies Limited",
    "In Stock": "49",
  },
  {
    SKU: "DM19292",
    Desc: "Dartline pump interface card",
    Category: "Fuel",
    Heading: "PDM192 - Dartline/Wayne Protocol",
    "Part Type": "PDM192 - Dartline/Wayne Protocol",
    "Unit Purpose": "Dartline pump interface card",
    "Model/Part Number": "PDM192",
    "Part Name": "PDM192: RS485",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "175",
    "Asset?": "No",
    "Primary Vendor": "Integration Technologies Limited",
    "In Stock": "56",
  },
  {
    SKU: "DM126",
    Desc: "LPG pump interface card",
    Category: "Fuel",
    Heading: "FDM126 - Email Protocol",
    "Part Type": "FDM126 - Email Protocol",
    "Unit Purpose": "LPG pump interface card",
    "Model/Part Number": "FDM126",
    "Part Name": "FDM126: Email Protocol",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "175",
    "Asset?": "",
    "Primary Vendor": "Integration Technologies Limited",
    "In Stock": "5",
  },
  {
    SKU: "POS Pole Assembly",
    Desc: "POS Pole Assembly",
    Category: "Poles & Mounts",
    Heading: "POS - Pole Mounting Solution",
    "Part Type": "POS - Pole Mounting Solution",
    "Unit Purpose": "POS Pole Assembly",
    "Model/Part Number": "KIT",
    "Part Name": "ATDEC + Spacepole POS Pole Solution",
    "Product Image": "",
    Wattage: "0",
    "Product Price (ex GST)": "399.3",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "420",
  },
  {
    SKU: "88149301162 88149301163",
    Desc: "POS Pole Assembly (Arm)",
    Category: "Poles & Mounts",
    Heading: "POS Pole Assembly (Arm)",
    "Part Type": "POS Pole Assembly (Arm)",
    "Unit Purpose": "",
    "Model/Part Number": "APA-A300 / APA-A200",
    "Part Name": "Atdec POS Pole solution - APA-A300 & APA-A200",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "100",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "140",
  },
  {
    SKU: "SPV1103-02",
    Desc: "POS Pole Assembly (Pole & Display Head)",
    Category: "Poles & Mounts",
    Heading: "POS Pole Assembly (Pole & Display Head)",
    "Part Type": "POS Pole Assembly (Pole & Display Head)",
    "Unit Purpose": "POS Pole Assembly (Pole & Display Head)",
    "Model/Part Number": "MSSPSPV1103",
    "Part Name": "Spacepole POS Pole solution - Back to back head and Pole",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "100",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "420",
  },
  {
    SKU: "88149301680",
    Desc: "POS Pole Assembly (Terminal Base)",
    Category: "Poles & Mounts",
    Heading: "POS Pole Assembly (Terminal Base)",
    "Part Type": "POS Pole Assembly (Terminal Base)",
    "Unit Purpose": "POS Pole Assembly (Terminal Base)",
    "Model/Part Number": "APA-B",
    "Part Name": "Atdec POS Pole solution - APA-B",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "100",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "420",
  },
  {
    SKU: "88149301120",
    Desc: "POS Pole Assembly (Display Head)",
    Category: "Poles & Mounts",
    Heading: "POS Pole Assembly (Display Head)",
    "Part Type": "POS Pole Assembly (Display Head)",
    "Unit Purpose": "POS Pole Assembly (Display Head)",
    "Model/Part Number": "2*APA-HA-45",
    "Part Name": "Atdec POS Pole solution - 2*APA-HA-45 + APA-HB2B-45",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "100",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "19",
  },
  {
    SKU: "88149301869",
    Desc: "POS Pole Assembly (Primary Pole)",
    Category: "Poles & Mounts",
    Heading: "POS Pole Assembly (Primary Pole)",
    "Part Type": "POS Pole Assembly (Primary Pole)",
    "Unit Purpose": "POS Pole Assembly (Primary Pole)",
    "Model/Part Number": "APS-HB2B-P400",
    "Part Name": "Atdec POS Pole solution - APS-HB2B-P400",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "100",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "412",
  },
  {
    SKU: "88149301764",
    Desc: "POS Pole Assembly (Terminal Holder)",
    Category: "Poles & Mounts",
    Heading: "POS Pole Assembly (Terminal Holder)",
    "Part Type": "POS Pole Assembly (Terminal Holder)",
    "Unit Purpose": "POS Pole Assembly (Terminal Holder)",
    "Model/Part Number": "APA-E-ICT220",
    "Part Name": "Atdec POS Pole solution - APA-E-ICT220",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "100",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "480",
  },
  {
    SKU: "",
    Desc: "DMG Holder",
    Category: "Poles & Mounts",
    Heading: "POS Pole Assembly (Terminal Holder)",
    "Part Type": "POS Pole Assembly (Terminal Holder)",
    "Unit Purpose": "",
    "Model/Part Number": "PS200",
    "Part Name": "PAX pole stand and terminal cradle - PS200",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "50",
    "Asset?": "No",
    "Primary Vendor": "PAX Technology",
    "In Stock": "0",
  },
  {
    SKU: "88149301167",
    Desc: "SW / GYG KDS / OTR App pickup window",
    Category: "Poles & Mounts",
    Heading: "POS Pole - Articulated Arm",
    "Part Type": "POS Pole - Articulated Arm",
    "Unit Purpose": "SW / GYG KDS / OTR App pickup window",
    "Model/Part Number": "APA-AA-P",
    "Part Name": "ATDEC articulating arm for POS pole (APA-AA-P)",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "200.52",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "32",
  },
  {
    SKU: "88149301160",
    Desc: "SW / GYG KDS / OTR App pickup window",
    Category: "Poles & Mounts",
    Heading: "POS Pole - Articulated Arm (Head )",
    "Part Type": "POS Pole - Articulated Arm (Head Mount)",
    "Unit Purpose": "SW / GYG KDS / OTR App pickup window",
    "Model/Part Number": "APA-HP",
    "Part Name": "ATDEC head unit for articulating arm for POS pole (APA-HP)",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "77.02",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "9",
  },
  {
    SKU: "",
    Desc: "Ccoffee KDS Pole Assembly",
    Category: "Poles & Mounts",
    Heading: "Coffee - Pole Mount Solution",
    "Part Type": "Coffee - Pole Mount Solution",
    "Unit Purpose": "Ccoffee KDS Pole Assembly",
    "Model/Part Number": "AWM-A46-B + AWM-P75G + AWM-FB",
    "Part Name": "ATDEC Ccoffee system - Whole Kit",
    "Product Image": "",
    Wattage: "0",
    "Product Price (ex GST)": "312.99",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "64",
  },
  {
    SKU: "88149301196",
    Desc: "Ccoffee KDS Pole Assembly - Monitor Arm/Head",
    Category: "Poles & Mounts",
    Heading: "Ccoffee KDS Pole Assembly -Head",
    "Part Type": "Ccoffee KDS Pole Assembly - Monitor Arm/Head",
    "Unit Purpose": "Ccoffee KDS Pole Assembly - Monitor Arm/Head",
    "Model/Part Number": "AWM-A46-B",
    "Part Name": "ATDEC Ccoffee system - Monitor Arm/Head (460mm)",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "156.26",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "196",
  },
  {
    SKU: "88149301838",
    Desc: "Ccoffee KDS Pole Assembly - Pole (750mm)",
    Category: "Poles & Mounts",
    Heading: "Ccoffee KDS Pole Assembly -Pole",
    "Part Type": "Ccoffee KDS Pole Assembly - Pole (750mm)",
    "Unit Purpose": "Ccoffee KDS Pole Assembly - Pole (750mm)",
    "Model/Part Number": "AWM-P75G",
    "Part Name": "ATDEC Ccoffee system - Pole (750mm)",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "116.76",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "64",
  },
  {
    SKU: "88149301354",
    Desc: "Ccoffee KDS Pole Assembly - Base",
    Category: "Poles & Mounts",
    Heading: "Ccoffee KDS Pole Assembly - Base",
    "Part Type": "Ccoffee KDS Pole Assembly - Base",
    "Unit Purpose": "Ccoffee KDS Pole Assembly - Base",
    "Model/Part Number": "AWM-FB",
    "Part Name": "ATDEC Ccoffee system - Base (AWM-FB)",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "39.97",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "126",
  },
  {
    SKU: "88149300590",
    Desc: "Moes / Diner / DT Pole",
    Category: "Poles & Mounts",
    Heading: "Secondary KDS - Pole Solution",
    "Part Type": "Secondary KDS - Pole Solution",
    "Unit Purpose": "Moes / Diner / DT Pole",
    "Model/Part Number": "SD-POS-HA",
    "Part Name": "ATDEC Moes POS Pole system (SD-POS-HA)",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "167.33",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "39",
  },
  {
    SKU: "88149300416",
    Desc: "Diner Articulated Wall Mount Arm",
    Category: "Poles & Mounts",
    Heading: "Wall Mount - Articulated Arm",
    "Part Type": "Wall Mount - Articulated Arm",
    "Unit Purpose": "Diner Articulated Wall Mount Arm",
    "Model/Part Number": "SD-AT-DW-BK",
    "Part Name":
      "SD-AT-DW-BK Spacedec Acrobat Articulated Wall Black (SD-AT-DW-BK)",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "249.872",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "20",
  },
  {
    SKU: "9.34176E+11",
    Desc: "BO Screen wall mount",
    Category: "Poles & Mounts",
    Heading: "Back Office - Monitor Wall Mount",
    "Part Type": "Back Office - Monitor Wall Mount",
    "Unit Purpose": "BO Screen wall mount",
    "Model/Part Number": "BT-LCD201",
    "Part Name": "Brateck 2 Piece LCD Wall Mount",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "11.55",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "29",
  },
  {
    SKU: "43MDI70FSD",
    Desc: "Adhoc: Landscape OTR/GyG/SW DMB",
    Category: "Digital Signs",
    Heading: 'Digital Signage - 43"',
    "Part Type": 'Digital Signage - 43"',
    "Unit Purpose": "Adhoc: Landscape OTR/GyG/SW DMB",
    "Model/Part Number": "43MDI70FSD",
    "Part Name": 'Mitsumaru 43" Screen',
    "Product Image": "",
    Wattage: "100",
    "Product Price (ex GST)": "730",
    "Asset?": "",
    "Primary Vendor": "Mitsumaru",
    "In Stock": "8",
  },
  {
    SKU: "8.80609E+11",
    Desc: "Landscape OTR/GyG/SW DMB",
    Category: "Digital Signs",
    Heading: 'Digital Signage - 49"',
    "Part Type": 'Digital Signage - 49"',
    "Unit Purpose": "Landscape OTR/GyG/SW DMB",
    "Model/Part Number": "49UH5F-H",
    "Part Name": 'LG 49" Screen',
    "Product Image": "image.png",
    Wattage: "140",
    "Product Price (ex GST)": "1110.16",
    "Asset?": "No",
    "Primary Vendor": "Unified Technology Solutions",
    "In Stock": "24",
  },
  {
    SKU: "8.80609E+11",
    Desc: "Portrait OTR DMB",
    Category: "Digital Signs",
    Heading: 'Digital Signage - 65"',
    "Part Type": 'Digital Signage - 65"',
    "Unit Purpose": "Portrait OTR DMB",
    "Model/Part Number": "65UH5F-H",
    "Part Name": 'LG 65" Screen',
    "Product Image": "image.png",
    Wattage: "260",
    "Product Price (ex GST)": "1898.4",
    "Asset?": "No",
    "Primary Vendor": "Unified Technology Solutions",
    "In Stock": "49",
  },
  {
    SKU: "8.8061E+11",
    Desc: "DT/Outdoor Digital Signage",
    Category: "Digital Signs",
    Heading: 'Digital Signage - 49" Outdoor Kiosk',
    "Part Type": 'Digital Signage - 49" Outdoor Kiosk',
    "Unit Purpose": "DT/Outdoor Digital Signage",
    "Model/Part Number": "49XE4F-H",
    "Part Name": "LG 49” Outdoor Kiosk Screen (w/ Stand)",
    "Product Image": "image.png",
    Wattage: "300",
    "Product Price (ex GST)": "6649.2",
    "Asset?": "No",
    "Primary Vendor": "Unified Technology Solutions",
    "In Stock": "30",
  },
  {
    SKU: "8.80609E+11",
    Desc: "Arneg screen",
    Category: "Digital Signs",
    Heading: 'Digital Signage - 13" (Arneg)',
    "Part Type": 'Digital Signage - 13" (Arneg)',
    "Unit Purpose": "Arneg screen",
    "Model/Part Number": "LH13QBREBGCXXY",
    "Part Name": '13" Samsung professional Display',
    "Product Image": "image.png",
    Wattage: "28",
    "Product Price (ex GST)": "357.6",
    "Asset?": "Yes",
    "Primary Vendor": "Amped Digital",
    "In Stock": "57",
  },
  {
    SKU: "88149300477",
    Desc: '43/49" Landscape Wall Mount Bracket',
    Category: "Poles & Mounts",
    Heading: "Landscape Wall Mount",
    "Part Type": "Landscape Wall Mount",
    "Unit Purpose": '43/49" Landscape Wall Mount Bracket',
    "Model/Part Number": "TH-3070-UF",
    "Part Name": 'Atdec (Landscape Wall Mount bracket for 49" DMB)',
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "90.91",
    "Asset?": "No",
    "Primary Vendor": "Unified Technology Solutions",
    "In Stock": "27",
  },
  {
    SKU: "88149301927",
    Desc: '49/65" Landscape Wall Mount Bracket',
    Category: "Poles & Mounts",
    Heading: "Portrait Wall Mount",
    "Part Type": "Portrait Wall Mount",
    "Unit Purpose": '49/65" Landscape Wall Mount Bracket',
    "Model/Part Number": "TH-3070-UFP",
    "Part Name": 'Atdec (Portrait wall mount bracket for 49" or 65")',
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "44.92",
    "Asset?": "No",
    "Primary Vendor": "Unified Technology Solutions",
    "In Stock": "78",
  },
  {
    SKU: "",
    Desc: "Drive Thru Ceiling Mount",
    Category: "Poles & Mounts",
    Heading: "Drive Thru Ceiling Mount",
    "Part Type": "Drive Thru Ceiling Mount",
    "Unit Purpose": "Drive Thru Ceiling Mount",
    "Model/Part Number": "FPCEILPTBLP",
    "Part Name": "Startech Digital Signage Ceiling Mount",
    "Product Image": "image.png",
    Wattage: "0",
    "Product Price (ex GST)": "199.09",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "0",
  },
  {
    SKU: "",
    Desc: "Outdoor LED media player",
    Category: "Digital Signs",
    Heading: "LED Media Player",
    "Part Type": "LED Media Player",
    "Unit Purpose": "Outdoor LED media player",
    "Model/Part Number": "TB50",
    "Part Name": "Novastar TB50 Media Player, light sensor, card",
    "Product Image": "image.png",
    Wattage: "360",
    "Product Price (ex GST)": "1483.78",
    "Asset?": "No",
    "Primary Vendor": "Dicolor",
    "In Stock": "0",
  },
  {
    SKU: "250-FB387-503ZP",
    Desc: "Secondary KDS PC / Adhoc Media Player",
    Category: "KDS",
    Heading: "Secondary KDS - Small Profile PC",
    "Part Type": "Secondary KDS - Small Profile PC",
    "Unit Purpose": "Secondary KDS PC / Adhoc Media Player",
    "Model/Part Number": "ZP-PI335J72F71:HF71:F72",
    "Part Name": "ZOTAC PRO (z-box), N4100, 4GB, 64GB eMMC",
    "Product Image": "image.png",
    Wattage: "20",
    "Product Price (ex GST)": "406",
    "Asset?": "Yes",
    "Primary Vendor": "Ocean Office Automation Pty Ltd",
    "In Stock": "95",
  },
  {
    SKU: "88972829478 1PCBS350-24FP-4G-AU",
    Desc: "Switch - Managed 24P",
    Category: "Network",
    Heading: "Switch - Managed 24P",
    "Part Type": "Switch - Managed 24P",
    "Unit Purpose": "Switch - Managed 24P",
    "Model/Part Number": "CBS350-24FP-4G-AU",
    "Part Name":
      "CBS350 Managed 24-port + CON-SNT-CBS350F2: SNTC-8X5XNBD CBS350 licence",
    "Product Image": "image.png",
    Wattage: "350",
    "Product Price (ex GST)": "1237.74",
    "Asset?": "Yes",
    "Primary Vendor": "Datacom",
    "In Stock": "15",
  },
  {
    SKU: "88972829376",
    Desc: "Switch - Managed 48P",
    Category: "Network",
    Heading: "Switch - Managed 48P",
    "Part Type": "Switch - Managed 48P",
    "Unit Purpose": "Switch - Managed 48P",
    "Model/Part Number": "CBS350-48FP-FX-AU",
    "Part Name":
      "CBS350 Managed 48-port + CON-SNT-CBS350F2: SNTC-8X5XNBD CBS350 licence",
    "Product Image": "image.png",
    Wattage: "740",
    "Product Price (ex GST)": "2953.18",
    "Asset?": "Yes",
    "Primary Vendor": "Datacom",
    "In Stock": "21",
  },
  {
    SKU: "C9200-48P-E V02",
    Desc: "Switch - Managed 48P (C9200)",
    Category: "Network",
    Heading: "Switch - Managed 48P (C9200)",
    "Part Type": "Switch - Managed 48P (C9200)",
    "Unit Purpose": "Switch - Managed 48P (C9200)",
    "Model/Part Number": "C9200-48P-E",
    "Part Name": "C9200-48P-E 9200 Switches | Cisco Catalyst 9200 Series",
    "Product Image": "image.png",
    Wattage: "740",
    "Product Price (ex GST)": "6478",
    "Asset?": "",
    "Primary Vendor": "Datacom",
    "In Stock": "4",
  },
  {
    SKU: "31P7D1X-CTO1WW SE350",
    Desc: "RSSU - SE350",
    Category: "Network",
    Heading: "RSSU - SE350",
    "Part Type": "RSSU - SE350",
    "Unit Purpose": "RSSU - SE350",
    "Model/Part Number": "SE350",
    "Part Name": "Lenovo ThinkSystem SE350(RSSU)",
    "Product Image": "image.png",
    Wattage: "200",
    "Product Price (ex GST)": "4020",
    "Asset?": "Yes",
    "Primary Vendor": "Nuago",
    "In Stock": "10",
  },
  {
    SKU: "81008720180 55-104255-01",
    Desc: "Site Wireless Access Point (WAP)",
    Category: "Network",
    Heading: "Wireless Access Point (WAP)",
    "Part Type": "Wireless Access Point (WAP)",
    "Unit Purpose": "Site Wireless Access Point (WAP)",
    "Model/Part Number": "CW916i-MR",
    "Part Name": "CW916i-MR",
    "Product Image": "image.png",
    Wattage: "30",
    "Product Price (ex GST)": "1331.15",
    "Asset?": "Yes",
    "Primary Vendor": "Datacom",
    "In Stock": "17",
  },
  {
    SKU: "88972811368 1PC1113-8PLTELA",
    Desc: "Site Router with POE",
    Category: "Network",
    Heading: "POE Router",
    "Part Type": "POE Router",
    "Unit Purpose": "Site Router with POE",
    "Model/Part Number": "C1113-8PLTELA",
    "Part Name":
      "Cisco: ISR 1100 4 Ports 802.3at POE Module\n : ISR 1100 G.FAST GE SFP Router + CON-SNTC11138PL: SNTC-8X5XNBD ISR + ISR-1100-POE4",
    "Product Image": "image.png",
    Wattage: "150",
    "Product Price (ex GST)": "2595.78",
    "Asset?": "Yes",
    "Primary Vendor": "Datacom",
    "In Stock": "5",
  },
  {
    SKU: "88972819034 1PC1127-8PLTEP",
    Desc: "Site Router",
    Category: "Network",
    Heading: "POE Router - (C1127)",
    "Part Type": "POE Router - (C1127)",
    "Unit Purpose": "Site Router",
    "Model/Part Number": "C1127-8PLTEP",
    "Part Name":
      "C1127-8PLTEP CISCO ISR 1100 8P XDSL GE SFP ROUTER PLUGGABLE SMS/GPS",
    "Product Image": "image.png",
    Wattage: "150",
    "Product Price (ex GST)": "1843",
    "Asset?": "",
    "Primary Vendor": "Telstra",
    "In Stock": "30",
  },
  {
    SKU: "4.25037E+11",
    Desc: "Site Phone Combo",
    Category: "Network",
    Heading: "VOIP Phone - Combo",
    "Part Type": "VOIP Phone - Combo",
    "Unit Purpose": "Site Phone Combo",
    "Model/Part Number": "Gigaset A690 IP",
    "Part Name": "Gigaset Handset & Base Station",
    "Product Image": "image.png",
    Wattage: "9.5",
    "Product Price (ex GST)": "151.2",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "22",
  },
  {
    SKU: "4.25037E+11",
    Desc: "Site Phone Handset",
    Category: "Network",
    Heading: "VOIP Phone - Handset",
    "Part Type": "VOIP Phone - Handset",
    "Unit Purpose": "Site Phone Handset",
    "Model/Part Number": "Gigaset AS690HX",
    "Part Name": "Gigaset Handset",
    "Product Image": "image.png",
    Wattage: "5",
    "Product Price (ex GST)": "77",
    "Asset?": "",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "40",
  },
  {
    SKU: "501973829879 505541601447",
    Desc: "Wifi extender Antenna (for Router)",
    Category: "Network",
    Heading: "Antenna - 4G Extender",
    "Part Type": "Antenna - 4G Extender",
    "Unit Purpose": "Wifi extender Antenna (for Router)",
    "Model/Part Number":
      "C897VAG-LTE-LA-K9 (400-SMAMSMAF-5 LCU400+B4BE-7-27-5SP+SMAF-TNCMAD)",
    "Part Name":
      "Outdoor Yagi Antenna suit Cisco B4BE-7-27(adapter nut, cable, receiver)",
    "Product Image": "image.png",
    Wattage: "5",
    "Product Price (ex GST)": "180.91",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "25",
  },
  {
    SKU: "4.77903E+11",
    Desc: "Pop-up POS / HJ / GYG QSR site / OPT",
    Category: "Network",
    Heading: "QSR Router - Teltonika",
    "Part Type": "QSR Router - Teltonika",
    "Unit Purpose": "Pop-up POS / HJ / GYG QSR site / OPT",
    "Model/Part Number": "NHT-RUT950-LTE",
    "Part Name": "Teltonika RUT950 LTE router 4G backup_all",
    "Product Image": "image.png",
    Wattage: "7",
    "Product Price (ex GST)": "349.09",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "18",
  },
  {
    SKU: "6.93536E+11",
    Desc: "Adhoc Network Dumb Switch",
    Category: "Network",
    Heading: "Dumb Switch - 16P",
    "Part Type": "Dumb Switch - 16P",
    "Unit Purpose": "Adhoc Network Dumb Switch",
    "Model/Part Number": "TL-SG116",
    "Part Name":
      "TP-Link  16-Port Unmanaged Gigabit Desktop/Wall Mounting Switch",
    "Product Image": "image.png",
    Wattage: "10",
    "Product Price (ex GST)": "85.86",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "7",
  },
  {
    SKU: "6.93536E+11",
    Desc: "Unmanaged switch for Adhoc needs ",
    Category: "Network",
    Heading: "Adhoc Network Unmanaged Switch",
    "Part Type": "Adhoc Network Dumb Switch",
    "Unit Purpose": "",
    "Model/Part Number": "TL-SG108 V6",
    "Part Name": "TP Link - 8-Port 10/100/1000Mbps Desktop Switch",
    "Product Image": "image.png",
    Wattage: "2.77",
    "Product Price (ex GST)": "84.9",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "26",
  },
  {
    SKU: "4.71291E+11",
    Desc: "Router/Modem for HJ / GYG QSR site",
    Category: "Network",
    Heading: "Draytek",
    "Part Type": "QSR Router - Draytek",
    "Unit Purpose": "Router for HJ / GYG QSR site",
    "Model/Part Number": "DV167",
    "Part Name": "Draytek Vigor167 VDSL2 35b Supervectoring Modem DV167",
    "Product Image": "image.png",
    Wattage: "12",
    "Product Price (ex GST)": "189",
    "Asset?": "Yes",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "2",
  },
  {
    SKU: "FG-40F P24680-04-02",
    Desc: "Firewall_all HJ / GYG QSR site",
    Category: "Network",
    Heading: "Fortinet 40F",
    "Part Type": "QSR - Network Firewall",
    "Unit Purpose": "Firewall_all HJ / GYG QSR site",
    "Model/Part Number": "FG-40F",
    "Part Name": "Fortinet 40F",
    "Product Image": "image.png",
    Wattage: "15",
    "Product Price (ex GST)": "856.9",
    "Asset?": "Yes",
    "Primary Vendor": "Nuago",
    "In Stock": "2",
  },
  {
    SKU: "A920-3AW-RE5-21EP",
    Desc: "POS - Payment Terminal (DMG)",
    Category: "Payment",
    Heading: "DMG Terminal- A920",
    "Part Type": "POS - Payment Terminal (DMG)",
    "Unit Purpose": "POS Payment Terminal",
    "Model/Part Number": "A920",
    "Part Name": "DMG Pax A920 - EFTPOS Payment Terminal",
    "Product Image": "image.png",
    Wattage: "5",
    "Product Price (ex GST)": "0",
    "Asset?": "No",
    "Primary Vendor": "DataMesh Group",
    "In Stock": "46",
  },
  {
    SKU: "",
    Desc: "OPT/HW - Payement Terminal (DMG)",
    Category: "Payment",
    Heading: "IM30",
    "Part Type": "OPT/HW - Payement Terminal (DMG)",
    "Unit Purpose": "",
    "Model/Part Number": "IM30",
    "Part Name": "DMG Pax IM30 - EFTPOS Payment Terminal",
    "Product Image": "image.png",
    Wattage: "",
    "Product Price (ex GST)": "0",
    "Asset?": "",
    "Primary Vendor": "DataMesh Group",
    "In Stock": "0",
  },
  {
    SKU: "L920-BC-1E0",
    Desc: "Payment Terminal - DMG Charging Cradle",
    Category: "Payment",
    Heading: "DMG Cradle",
    "Part Type": "Payment Terminal - DMG Charging Cradle",
    "Unit Purpose": "Payment Terminal - Charging Cradle",
    "Model/Part Number": "A920 Charging Cradle",
    "Part Name": "DMG Pax A920 - Charging Cradle",
    "Product Image": "image.png",
    Wattage: "5",
    "Product Price (ex GST)": "0",
    "Asset?": "No",
    "Primary Vendor": "DataMesh Group",
    "In Stock": "23",
  },
  {
    SKU: "TBC",
    Desc: "GYG - POS Server/Office PC",
    Category: "QSRs",
    Heading: "GYG - POS Server/Office PC",
    "Part Type": "GYG - POS Server/Office PC",
    "Unit Purpose": "",
    "Model/Part Number": "TBC",
    "Part Name": "Dell OptiPlex 7070",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "1274.9",
    "Asset?": "",
    "Primary Vendor": "GyG Head Office",
    "In Stock": "0",
  },
  {
    SKU: "1470G2D-2-R-INT",
    Desc: "GYG - Barcode Scanner",
    Category: "QSRs",
    Heading: "GYG - Barcode Scanner",
    "Part Type": "GYG - Barcode Scanner",
    "Unit Purpose": "GYG Barcode Scanner",
    "Model/Part Number": "DS2208",
    "Part Name": "Zebra Scanner Kit DS2208 2D-SR USB BLK",
    "Product Image": "image.png",
    Wattage: "21",
    "Product Price (ex GST)": "128.7",
    "Asset?": "Yes",
    "Primary Vendor": "GyG Head Office",
    "In Stock": "4",
  },
  {
    SKU: "TBC",
    Desc: "GYG - KDS",
    Category: "QSRs",
    Heading: "GYG - KDS",
    "Part Type": "GYG - KDS",
    "Unit Purpose": "",
    "Model/Part Number": "TBC",
    "Part Name":
      'YUNO " B" POS Terminal, 21.5" Screen, Kaby Lake i3-7100U , 8 GB RAM,\n250 GB SSD, Black, Win 10 IoT Value LTSC 2021',
    "Product Image": "9.jpg",
    Wattage: "",
    "Product Price (ex GST)": "2335",
    "Asset?": "",
    "Primary Vendor": "GyG Head Office",
    "In Stock": "2",
  },
  {
    SKU: "ART-04606",
    Desc: "GYG - POS",
    Category: "QSRs",
    Heading: "GYG - POS",
    "Part Type": "GYG - POS",
    "Unit Purpose": "GYG FOH POS",
    "Model/Part Number": "ART-04606",
    "Part Name":
      'YUNO " B" Base, 15.1 Screen, i3-7100, 8Gb DDR4, WIN10 IOT Enterprise 64Bit',
    "Product Image": "2023-06-20 16_04_27-YUNO-B-datasheet-ENG.pdf.jpg",
    Wattage: "",
    "Product Price (ex GST)": "1980",
    "Asset?": "Yes",
    "Primary Vendor": "GyG Head Office",
    "In Stock": "2",
  },
  {
    SKU: "ART-03260",
    Desc: "GYG - POS",
    Category: "QSRs",
    Heading: "GYG - POS",
    "Part Type": "GYG - POS",
    "Unit Purpose": "",
    "Model/Part Number": "ART-03260",
    "Part Name": "YUNO Integrated 10.1 LED Customer Display Black",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "400",
    "Asset?": "",
    "Primary Vendor": "GyG Head Office",
    "In Stock": "3",
  },
  {
    SKU: "ART-02890",
    Desc: "GYG - Receipt Printer",
    Category: "QSRs",
    Heading: "GYG - Receipt Printer",
    "Part Type": "GYG - Receipt Printer",
    "Unit Purpose": "GYG Receipt Printer",
    "Model/Part Number": "ART-02890",
    "Part Name": "AURES ODP333 THERMAL PRINTER",
    "Product Image": "image.png",
    Wattage: "",
    "Product Price (ex GST)": "390",
    "Asset?": "Yes",
    "Primary Vendor": "GyG Head Office",
    "In Stock": "3",
  },
  {
    SKU: "TBC",
    Desc: "GYG - Cash Drawer",
    Category: "QSRs",
    Heading: "GYG - Cash Drawer",
    "Part Type": "GYG - Cash Drawer",
    "Unit Purpose": "GYG Cash Drawer",
    "Model/Part Number": "ART-03482",
    "Part Name": "AURES S430 CASH DRAWER",
    "Product Image": "image.png",
    Wattage: "",
    "Product Price (ex GST)": "110",
    "Asset?": "No",
    "Primary Vendor": "GyG Head Office",
    "In Stock": "6",
  },
  {
    SKU: "TBC",
    Desc: "GYG - Food Sticker Printer",
    Category: "QSRs",
    Heading: "GYG - Food Sticker Printer",
    "Part Type": "GYG - Food Sticker Printer",
    "Unit Purpose": "GYG Food Wrap Stickers",
    "Model/Part Number": "SLP-DX420",
    "Part Name": "Bixolon - EG Thermal Printer",
    "Product Image": "image.png",
    Wattage: "",
    "Product Price (ex GST)": "430",
    "Asset?": "Yes",
    "Primary Vendor": "GyG Head Office",
    "In Stock": "4",
  },
  {
    SKU: "TBC",
    Desc: "GYG - Food Expiration Sticker Printer",
    Category: "QSRs",
    Heading: "GYG - Food Expiration Sticker Printer",
    "Part Type": "GYG - Food Expiration Sticker Printer",
    "Unit Purpose": "GYG Food expiry time sticker printer",
    "Model/Part Number": "9417+",
    "Part Name": "Monarch FreshMarx  printer",
    "Product Image": "image.png",
    Wattage: "",
    "Product Price (ex GST)": "1300",
    "Asset?": "Yes",
    "Primary Vendor": "Avery Dennison",
    "In Stock": "1",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "HDMI To VGA Converter Cable 2m Male To Male",
    "Part Type": "POS (Display Backward Compatibility / KDS system",
    "Unit Purpose": "",
    "Model/Part Number": "RC-HDMIVGA-2",
    "Part Name": "HDMI To VGA Converter Cable 2m Male To Male",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "20.08",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "HDMI To VGA Converter/Adaptor",
    "Part Type": "Moes, QSR, DT KDS NUCs, Adhoc use",
    "Unit Purpose": "",
    "Model/Part Number": "CB8W-CVT-HDMIVGA",
    "Part Name": "HDMI To VGA Converter/Adaptor",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "26.76",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "VGA Monitor Cable 2m HD15 Pin Male To Male",
    "Part Type": "Display cable for Misc. Monitor",
    "Unit Purpose": "",
    "Model/Part Number": "CB8W-RC-3050F",
    "Part Name": "VGA Monitor Cable 2m HD15 Pin Male To Male",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "7.3",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "USB-C to VGA cable - 1M",
    "Part Type": "Display for NUC (needed for NUC <= Gen10)",
    "Unit Purpose": "",
    "Model/Part Number": "CDP2VGAMM1MB",
    "Part Name": "USB-C to VGA cable - 1M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "73.01",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "Legend - SPIRAL BINDING 12MM BLACK 1per/m",
    "Part Type": "Cable Wrap Kit",
    "Unit Purpose": "",
    "Model/Part Number": "SB12BK-150",
    "Part Name": "Legend - SPIRAL BINDING 12MM BLACK 1per/m",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "2.6",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "HDMI cable M-M 1m",
    "Part Type": "BO Monitor, POS, Ccoffee Customer Face",
    "Unit Purpose": "",
    "Model/Part Number": "CBAT-HDMI-MM-1",
    "Part Name": "HDMI cable M-M 1m",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "4.91",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "USB A to B Cable 3m",
    "Part Type": "Moes, QSR, KDS, CFS, Receipt Printer",
    "Unit Purpose": "",
    "Model/Part Number": "CBAT-USB-AB-3M",
    "Part Name": "USB A to B Cable 3m",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "2.23",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "USB A to B Cable 2m",
    "Part Type": "Moes, QSR, KDS, CFS, Receipt Printer",
    "Unit Purpose": "",
    "Model/Part Number": "USB2HAB2M",
    "Part Name": "USB A to B Cable 2m",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "1.93",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "Ugreen 2.0m USB Type-C to USB-B Cable - Black",
    "Part Type": "AIO (v2) & CFS (Touch Screen Function)",
    "Unit Purpose": "",
    "Model/Part Number": "50446",
    "Part Name": "Ugreen 2.0m USB Type-C to USB-B Cable - Black",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "6.84",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "Clover Leaf IEC Power Cable 5M",
    "Part Type": "ELO Ccoffee Touch Screen",
    "Unit Purpose": "",
    "Model/Part Number": "HPL240/CLB5",
    "Part Name": "Clover Leaf IEC Power Cable 5M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "9.25",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "Kettle IEC Power Cable 2m",
    "Part Type": "Ad Hoc Kettle Power Cable",
    "Unit Purpose": "",
    "Model/Part Number": "RA-K9-2MT",
    "Part Name": "Kettle IEC Power Cable 2m",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "4.49",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "Aten Petite 2 Port USB VGA KVM Switch with Audio",
    "Part Type": "Adhoc 2 PC - 1 Display (legacy use)",
    "Unit Purpose": "",
    "Model/Part Number": "CS-62US",
    "Part Name": "Aten Petite 2 Port USB VGA KVM Switch with Audio",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "54.09",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "2 Port USB HDMI/Audio Cable KVM Switch with Remote Port Selector",
    "Part Type": "Adhoc 2 PC - 1 Display (legacy use)",
    "Unit Purpose": "",
    "Model/Part Number": "ATEN CS692",
    "Part Name":
      "2 Port USB HDMI/Audio Cable KVM Switch with Remote Port Selector",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "105.9",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "Micro-USB Cable with Right-Angled Connectors - M/M - 2m",
    "Part Type": "DMG Terminal Power Cable",
    "Unit Purpose": "",
    "Model/Part Number": "USB2HAB2M",
    "Part Name": "Micro-USB Cable with Right-Angled Connectors - M/M - 2m",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "10.1",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT5E BLUE PATCH LEAD 0.3 M",
    "Part Type": "Network Comms",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT5EBL0.3",
    "Part Name": "CAT5E BLUE PATCH LEAD 0.3 M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "0.96",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT5E BLUE PATCH LEAD 0.5M",
    "Part Type": "Network Comms",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT5EBL0.5",
    "Part Name": "CAT5E BLUE PATCH LEAD 0.5M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "1.16",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT5E BLUE PATCH LEAD 1M",
    "Part Type": "Network Comms",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT5EBL1",
    "Part Name": "CAT5E BLUE PATCH LEAD 1M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "1.53",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT5E BLUE PATCH LEAD 2M",
    "Part Type": "Network Comms",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT5EBL2",
    "Part Name": "CAT5E BLUE PATCH LEAD 2M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "2.54",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT6 PURPLE PATCH LEAD 0.5M",
    "Part Type": "WEX / Quest pin pad Comms",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT6PU0.5",
    "Part Name": "CAT6 PURPLE PATCH LEAD 0.5M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "2.13",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT6 PURPLE PATCH LEAD 1M",
    "Part Type": "WEX / Quest pin pad Comms",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT6PU1",
    "Part Name": "CAT6 PURPLE PATCH LEAD 1M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "2.57",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT6 PURPLE PATCH LEAD 2M",
    "Part Type": "WEX / Quest pin pad Comms",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT6PU2",
    "Part Name": "CAT6 PURPLE PATCH LEAD 2M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "3.76",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT6 ORANGE PATCH LEAD 0.5M",
    "Part Type": "Digital Signage",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT6OR0.5",
    "Part Name": "CAT6 ORANGE PATCH LEAD 0.5M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "2.13",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT6 ORANGE PATCH LEAD 1.5M",
    "Part Type": "Digital Signage",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT6OR1.5",
    "Part Name": "CAT6 ORANGE PATCH LEAD 1.5M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "2.97",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT6 BLACK PATCH LEAD 0.5M",
    "Part Type": "Safe Comms",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT6BK0.5",
    "Part Name": "CAT6 BLACK PATCH LEAD 0.5M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "2.13",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT6 BLACK PATCH LEAD 3M",
    "Part Type": 'Safe Comms & 13" Arneg signage',
    "Unit Purpose": "",
    "Model/Part Number": "HCAT6BK3",
    "Part Name": "CAT6 BLACK PATCH LEAD 3M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "4.5",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
  {
    SKU: "",
    Desc: "Cable",
    Category: "Cables",
    Heading: "CAT6 BLACK PATCH LEAD 5M",
    "Part Type": "SSO / Adhoc Use",
    "Unit Purpose": "",
    "Model/Part Number": "HCAT6BK5",
    "Part Name": "CAT6 BLACK PATCH LEAD 5M",
    "Product Image": "",
    Wattage: "",
    "Product Price (ex GST)": "6.87",
    "Asset?": "No",
    "Primary Vendor": "Australia Online Computers",
    "In Stock": "",
  },
];
const categories = [
  { id: 1, name: "POS" },
  { id: 2, name: "KDS" },
  { id: 3, name: "Back Office" },
  { id: 4, name: "Network" },
  { id: 5, name: "Fuel" },
  { id: 6, name: "Poles & Mounts" },
  { id: 7, name: "Digital Signs" },
  { id: 8, name: "Payment" },
  { id: 9, name: "QSRs" },
  { id: 10, name: "MISC" },
  { id: 11, name: "Cables" },
];
module.exports = { products, categories };
